version: '3.8'

services:
  forgeflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forgeflow-v2
    restart: unless-stopped
    ports:
      - "3000:3000"  # Main application
      - "9090:9090"  # Metrics endpoint
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO=${GITHUB_REPO}
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgresql://forgeflow:forgeflow@postgres:5432/forgeflow
    volumes:
      - ./logs:/app/logs
      - ./.worktrees:/app/.worktrees
      - ./data:/app/data
    networks:
      - forgeflow-network
    depends_on:
      - redis
      - postgres
      - prometheus

  redis:
    image: redis:7-alpine
    container_name: forgeflow-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - forgeflow-network
    command: redis-server --appendonly yes

  postgres:
    image: postgres:15-alpine
    container_name: forgeflow-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=forgeflow
      - POSTGRES_PASSWORD=forgeflow
      - POSTGRES_DB=forgeflow
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - forgeflow-network

  prometheus:
    image: prom/prometheus:latest
    container_name: forgeflow-prometheus
    restart: unless-stopped
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - forgeflow-network

  grafana:
    image: grafana/grafana:latest
    container_name: forgeflow-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=redis-datasource
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/datasources:/etc/grafana/provisioning/datasources
    networks:
      - forgeflow-network
    depends_on:
      - prometheus

  nginx:
    image: nginx:alpine
    container_name: forgeflow-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - forgeflow-network
    depends_on:
      - forgeflow

networks:
  forgeflow-network:
    driver: bridge

volumes:
  redis-data:
  postgres-data:
  prometheus-data:
  grafana-data: