global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'forgeflow'
    static_configs:
      - targets: ['forgeflow:9090']
        labels:
          service: 'forgeflow-orchestrator'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        labels:
          service: 'redis-cache'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
        labels:
          service: 'postgres-db'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['forgeflow:9100']
        labels:
          service: 'node-metrics'