apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
  namespace: forgeflow-redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: auth
    app.kubernetes.io/part-of: forgeflow-v2
type: Opaque
stringData:
  # Base64 encode these values in production
  redis-password: "forgeflow2024!"
  admin-password: "admin2024!"
  forgeflow-password: "ff2app2024!"
  lock-password: "lock2024!"
  team-password: "team2024!"
  monitor-password: "monitor2024!"
  backup-password: "backup2024!"
  metrics-password: "metrics2024!"
  sentinel-password: "sentinel2024!"
  
  # Redis ACL configuration
  redis-acl.conf: |
    user admin on >${REDIS_ADMIN_PASSWORD} ~* &* +@all
    user forgeflow on >${REDIS_FORGEFLOW_PASSWORD} ~forgeflow:* ~locks:* ~tasks:* ~teams:* ~sessions:* +@read +@write +@list +@hash +@set +@stream +@pubsub +ping +info +client +eval +evalsha -@dangerous
    user lockservice on >${REDIS_LOCK_PASSWORD} ~locks:* ~sessions:* +@read +@write +@string +ping +eval +evalsha +expire +ttl +exists +del
    user teamcomm on >${REDIS_TEAM_PASSWORD} ~teams:* ~messages:* ~notifications:* +@read +@write +@pubsub +@stream +ping +info
    user monitor on >${REDIS_MONITOR_PASSWORD} ~* +@read +ping +info +config|get +client|list +memory +latency -@write -@admin
    user backup on >${REDIS_BACKUP_PASSWORD} ~* +@read +ping +info +bgsave +lastsave +debug|object -@write -@admin
    user metrics on >${REDIS_METRICS_PASSWORD} ~* +@read +ping +info +config|get +client +memory +latency +slowlog -@write -@admin
    user default off